apiVersion: v1
kind: ConfigMap
metadata:
  name: logstash-config
  labels:
    app: logstash
data:
  logstash.yml: |
    http.host: "0.0.0.0"
    path.config: /usr/share/logstash/pipeline
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: logstash-pipeline
  labels:
    app: logstash
data:
  logstash.conf: |
    input {
      beats {
        port => 5044
      }
    }
    filter {
      mutate {
        remove_field => [ "agent", "container", "ecs", "event", "input", "log", "tags" ]
      }
      mutate {
        rename => {
          "[host][name]" => "node"
          "[kubernetes][namespace]" => "namespace"
          "[kubernetes][pod][name]" => "pod"
          "[kubernetes][container][name]" => "container"
        }
      }
      mutate {
        remove_field => [ "host", "kubernetes" ]
      }
    }
    output {
      elasticsearch {
        hosts => [ "https://elasticsearch-es-http:9200" ]
        ssl_certificate_verification => false
        user => "elastic"
        password => "${elastic}"
        index => "stdout" 
      }
    }
